apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
    group: {{ .Values.app.group }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        group: {{ .Values.app.group }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum | trunc 10}}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.app.container.image }}:{{ .Values.app.container.version }}
          imagePullPolicy: "Always"
          command: ["/app/storage-service", "server"]
          ports:
            - containerPort: {{ .Values.app.container.ports.http }}
            - containerPort: {{ .Values.app.container.ports.grpc }}
          volumeMounts:
            - name: {{ .Values.app.name }}-config
              mountPath: /app/config.yml
              subPath: config.yml
              readOnly: true
      volumes:
        - name: {{ .Values.app.name }}-config
          configMap:
            name: {{ .Values.app.name }}-configmap