app:
  name: storage-service
  group: app
  replicaCount: 1
  container:
    image: krobus00/storage-service
    version: v0.1.1
    ports:
      http: 3001
      grpc: 5001
      metrics: 7001
  service:
    type: ClusterIP
    httpPort: 9081
    grpcPort: 9181
    metricsPort: 7000
